<?php
// module/Album/view/album/album/delete.phtml:

$title = 'Hapus album';
$url   = $this->url('album', ['action' => 'delete', 'id' => $id]);

$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Apakah Anda yakin ingin menghapus
    "<?= $this->escapeHtml($album->title) ?>" oleh
    "<?= $this->escapeHtml($album->artist) ?>"?
</p>

<form action="<?= $url ?>" method="post">
    <div class="form-group">
        <input type="hidden" name="id" value="<?= (int) $album->id ?>" />
        <input type="submit" class="btn btn-danger" name="del" value="Ya" />
        <input type="submit" class="btn btn-success" name="del" value="Tidak" />
    </div>
</form>