<?php
// module/Album/view/album/album/index.phtml:

$title = 'My albums';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('album', ['action' => 'add']) ?>" class="btn btn-primary">Tambah Album</a>
</p>

<table class="table table-hover table-bordered">
    <tr class="thead-dark">
        <th>Title</th>
        <th>Artist</th>
        <th>Aksi</th>
    </tr>
    <?php foreach ($album as $album) : ?>
        <tr>
            <td><?= $this->escapeHtml($album->title) ?></td>
            <td><?= $this->escapeHtml($album->artist) ?></td>
            <td>
                <a href="<?= $this->url('album', ['action' => 'edit', 'id' => $album->id]) ?>" class="badge badge-warning">Edit</a>
                <a href="<?= $this->url('album', ['action' => 'delete', 'id' => $album->id]) ?>" class="badge badge-danger">Hapus</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>