<?php
// module/Album/view/album/album/index.phtml:

$title = 'My Albums';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('album', ['action' => 'add']) ?>" class="btn btn-primary">Tambah Album</a>
</p>

<table class="table table-hover table-bordered table-head-bg-info table-bordered-bd-info mt-4">
    <tr class="bg-primary text-white">
        <th>#</th>
        <th>Title</th>
        <th>Artist</th>
        <th>Aksi</th>
    </tr>
    <?php $i = 1; ?>
    <?php foreach ($this->paginator as $album) : ?>
        <tr>
            <td align="center" width="10"><?= $this->escapeHtml($i) ?></td>
            <td><?= $this->escapeHtml($album->title) ?></td>
            <td><?= $this->escapeHtml($album->artist) ?></td>
            <td>
                <a style="text-decoration:none" href="<?= $this->url('album', ['action' => 'edit', 'id' => $album->id]) ?>">
                    <button type="button" class="btn btn-icon btn-round btn-warning">
                        <i class="fa fa-pencil-alt"></i>
                    </button>
                </a>
                <a style="text-decoration:none" href="<?= $this->url('album', ['action' => 'delete', 'id' => $album->id]) ?>">
                    <button type="button" class="btn btn-icon btn-round btn-danger">
                        <i class="fa fa-trash-alt"></i>
                    </button>
                </a>
            </td>
        </tr>
        <?php $i++; ?>
    <?php endforeach; ?>
</table>
<?= $this->paginationControl(
    // The paginator object:
    $this->paginator,
    // The scrolling style:
    'sliding',
    // The partial to use to render the control:
    'partial/paginator',
    // The route to link to when a user clicks a control link:
    ['route' => 'album']
) ?>