<?php

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">

<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Laminas MVC Skeleton')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink([
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'
    ])
        ->prependStylesheet($this->basePath('atlantistmp/assets/css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('atlantistmp/assets/css/atlantis.min.css'))
    ?>

    <!-- Fonts and icons -->
    <script src="<?= $this->basePath('atlantistmp/assets/js/plugin/webfont/webfont.min.js') ?>"></script>
    <script>
        WebFont.load({
            google: {
                "families": ["Lato:300,400,700,900"]
            },
            custom: {
                "families": ["Flaticon", "Font Awesome 5 Solid", "Font Awesome 5 Regular", "Font Awesome 5 Brands", "simple-line-icons"],
                urls: ['<?= $this->basePath('atlantistmp/assets/css/fonts.min.css') ?>']
            },
            active: function() {
                sessionStorage.fonts = true;
            }
        });
    </script>

    <!-- Scripts -->
    <?= $this->headScript() ?>
</head>

<body>
    <div class="wrapper">
        <div class="main-header">
            <!-- Logo Header -->
            <div class="logo-header" data-background-color="blue">

                <a href="<?= $this->url('home') ?>" class="logo">
                    <img src="<?= $this->basePath('img/laminas-logo.svg') ?>" alt="navbar brand" class="navbar-brand" width="auto" height="50px">
                </a>
                <button class="navbar-toggler sidenav-toggler ml-auto" type="button" data-toggle="collapse" data-target="collapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon">
                        <i class="icon-menu"></i>
                    </span>
                </button>
                <button class="topbar-toggler more"><i class="icon-options-vertical"></i></button>
                <div class="nav-toggle">
                    <button class="btn btn-toggle toggle-sidebar">
                        <i class="icon-menu"></i>
                    </button>
                </div>
            </div>
            <!-- End Logo Header -->

            <!-- Navbar Header -->
            <nav class="navbar navbar-header navbar-expand-lg" data-background-color="blue2">
                <div class="container-fluid">
                    <div class="collapse" id="search-nav">
                        <form class="navbar-left navbar-form nav-search mr-md-3">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <button type="submit" class="btn btn-search pr-1">
                                        <i class="fa fa-search search-icon"></i>
                                    </button>
                                </div>
                                <input type="text" placeholder="Cari ..." class="form-control">
                            </div>
                        </form>
                    </div>
                    <ul class="navbar-nav topbar-nav ml-md-auto align-items-center">
                        <li class="nav-item toggle-nav-search hidden-caret">
                            <a class="nav-link" data-toggle="collapse" href="#search-nav" role="button" aria-expanded="false" aria-controls="search-nav">
                                <i class="fa fa-search"></i>
                            </a>
                        </li>
                        <li class="nav-item dropdown hidden-caret">
                            <div class="text-white">
                                <span id="tgldate"></span> | <span id="clock"></span>
                            </div>
                        </li>
                        <li class="nav-item dropdown hidden-caret">
                            <a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#" aria-expanded="false">
                                <div class="avatar-sm">
                                    <img src="<?= $this->basePath('atlantistmp/assets/img/profile.jpg') ?>" alt="..." class="avatar-img rounded-circle">
                                </div>
                            </a>
                            <ul class="dropdown-menu dropdown-user animated fadeIn">
                                <div class="dropdown-user-scroll scrollbar-outer">
                                    <li>
                                        <div class="user-box">
                                            <div class="avatar-lg"><img src="<?= $this->basePath('atlantistmp/assets/img/profile.jpg') ?>" alt="image profile" class="avatar-img rounded"></div>
                                            <div class="u-text">
                                                <h4>Hizrian</h4>
                                                <p class="text-muted">hello@example.com</p><a href="profile.html" class="btn btn-xs btn-secondary btn-sm">View Profile</a>
                                            </div>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="#">My Profile</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="#">Account Setting</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="#">Logout</a>
                                    </li>
                                </div>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
            <!-- End Navbar -->
        </div>

        <!-- Sidebar -->
        <div class="sidebar sidebar-style-2">
            <div class="sidebar-wrapper scrollbar scrollbar-inner">
                <div class="sidebar-content">
                    <div class="user">
                        <div class="avatar-sm float-left mr-2">
                            <img src="<?= $this->basePath('atlantistmp/assets/img/profile.jpg') ?>" alt="..." class="avatar-img rounded-circle">
                        </div>
                        <div class="info">
                            <a data-toggle="collapse" href="<?= $this->url('home') ?>" aria-expanded="true">
                                <span>
                                    Febri Ramandha
                                    <span class="user-level">Administrator</span>
                                </span>
                            </a>
                            <div class="clearfix"></div>

                        </div>
                    </div>
                    <ul class="nav nav-primary">
                        <li class="nav-item active">
                            <a data-toggle="collapse" href="<?= $this->url('home') ?>" class="collapsed" aria-expanded="false">
                                <i class="fas fa-home"></i>
                                <p>Home</p>
                            </a>
                        </li>
                        <li class="nav-section">
                            <span class="sidebar-mini-icon">
                                <i class="fa fa-ellipsis-h"></i>
                            </span>
                            <h4 class="text-section">Components</h4>
                        </li>
                        <li class="nav-item">
                            <a data-toggle="collapse" href="<?= $this->url('album') ?>">
                                <i class="fas fa-pen-square"></i>
                                <p>Album</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a data-toggle="collapse" href="<?= $this->url('blog') ?>">
                                <i class="fas fa-table"></i>
                                <p>Blog</p>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- End Sidebar -->

        <!-- Content -->
        <div class="main-panel">
            <div class="content">
                <div class="page-inner">

                    <?= $this->navigation('navigation')
                        ->breadcrumbs()
                        ->setMinDepth(0)
                        ->setPartial('partial/breadcrumb') ?>

                    <?= $this->content ?>

                </div>
            </div>

            <footer class="footer">
                <div class="container-fluid">
                    <div class="copyright ml-auto">
                        Copyright &copy; <?= date('Y') ?>, made with <i class="fa fa-heart heart text-danger"></i> by Febri Ramandha
                    </div>
                </div>
            </footer>
        </div>
        <!-- End Content -->
    </div>


    <!--   Core JS Files   -->
    <?= $this->inlineScript()
        // ->prependFile($this->basePath('atlantistmp/assets/js/demo.js'))
        // ->prependFile($this->basePath('atlantistmp/assets/js/setting-demo.js'))
        // ->prependFile($this->basePath('atlantistmp/assets/js/atlantis.min.js'))
        ->prependFile($this->basePath('atlantistmp/assets/js/plugin/jqvmap/maps/jquery.vmap.world.js'))
        ->prependFile($this->basePath('atlantistmp/assets/js/plugin/jqvmap/jquery.vmap.min.js'))
        ->prependFile($this->basePath('atlantistmp/assets/js/plugin/bootstrap-notify/bootstrap-notify.min.js'))
        ->prependFile($this->basePath('atlantistmp/assets/js/plugin/datatables/datatables.min.js'))
        ->prependFile($this->basePath('atlantistmp/assets/js/plugin/jquery.sparkline/jquery.sparkline.min.js'))
        ->prependFile($this->basePath('atlantistmp/assets/js/plugin/chart.js/chart.min.js'))
        ->prependFile($this->basePath('atlantistmp/assets/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js'))
        ->prependFile($this->basePath('atlantistmp/assets/js/plugin/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js'))
        ->prependFile($this->basePath('atlantistmp/assets/js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js'))
        ->prependFile($this->basePath('atlantistmp/assets/js/core/popper.min.js'))
        ->prependFile($this->basePath('atlantistmp/assets/js/core/jquery.3.2.1.min.js'))
    ?>

    <script src="<?= $this->basePath('atlantistmp/assets/js/atlantis.min.js') ?>"></script>

    <script type="text/javascript">
        setInterval(() => {
            var namahari = "Minggu Senin Selasa Rabu Kamis Jumat Sabtu";
            namahari = namahari.split(" ");
            var tgl = new Date();
            var namabulan =
                "Januari Februari Maret April Mei Juni Juli Agustus September Oktober November Desember";
            namabulan = namabulan.split(" ");
            var hari = tgl.getDay();
            var tanggal = tgl.getDate();
            var bulan = tgl.getMonth();
            var tahun = tgl.getFullYear();
            var tgllengkap =
                namahari[hari] + ", " +
                tanggal + " " +
                namabulan[bulan] + " " +
                tahun;
            var tgldate = document.getElementById("tgldate");
            tgldate.innerHTML = tgllengkap;

            let date = new Date();
            let clock = document.getElementById("clock");
            clock.innerHTML =
                date.getHours() + ":" + date.getMinutes() + ":" + date.getSeconds();
        }, 1000);
    </script>

</body>

</html>